import NavBar from './components/NavBar';
import Footer from './components/Footer';
import './globals.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Zachs recipe app',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-primary-light`}>
        <NavBar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
